### ISSUE TITLE
CLWD dataset is required.

### ISSUE THREAD

**Issue by cksthf3211** [MRUIL/WatermarkRemoval-WDNet-WACV2021#16]
Hello.

I would like to use CLWD Dataset for research purposes.

It would be a great honor if you could share it.

CLWD(train, test, watermark_logo) dataset is required.

    |-- CLWD
    |      |-- train
    |      |-- test
    |      |-- watermark_logo

json@kyonggi.ac.kr

**Comment by MRUIL** [comment]
Hi, we provided the dataset link, and you can download it if needed.
